// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// haversine_cpp
double haversine_cpp(double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _stopdetection_haversine_cpp(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_cpp(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// haversine_vec
NumericVector haversine_vec(NumericVector lat1, NumericVector lon1, NumericVector lat2, NumericVector lon2);
RcppExport SEXP _stopdetection_haversine_vec(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_vec(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// haversine_seq
NumericVector haversine_seq(NumericVector lat, NumericVector lon);
RcppExport SEXP _stopdetection_haversine_seq(SEXP latSEXP, SEXP lonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_seq(lat, lon));
    return rcpp_result_gen;
END_RCPP
}
// stopFinder_cpp
IntegerVector stopFinder_cpp(NumericVector lat, NumericVector lon, NumericVector time, double thetaD, double thetaT);
RcppExport SEXP _stopdetection_stopFinder_cpp(SEXP latSEXP, SEXP lonSEXP, SEXP timeSEXP, SEXP thetaDSEXP, SEXP thetaTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type thetaD(thetaDSEXP);
    Rcpp::traits::input_parameter< double >::type thetaT(thetaTSEXP);
    rcpp_result_gen = Rcpp::wrap(stopFinder_cpp(lat, lon, time, thetaD, thetaT));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stopdetection_haversine_cpp", (DL_FUNC) &_stopdetection_haversine_cpp, 4},
    {"_stopdetection_haversine_vec", (DL_FUNC) &_stopdetection_haversine_vec, 4},
    {"_stopdetection_haversine_seq", (DL_FUNC) &_stopdetection_haversine_seq, 2},
    {"_stopdetection_stopFinder_cpp", (DL_FUNC) &_stopdetection_stopFinder_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_stopdetection(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
