#' Move Merger
#'
#' Discards move events (tracks) between stop events that should be discarded
#' during merging. This is based on the researcher-decided total number of
#' allowable locations that the discarded track can consist of, as well as a
#' maximum total time length that may elapse. Tracks are merged into the
#' preceding stop or excluded. Future versions of this should consider assigning
#' to the closest stop for action = merge
#'
#' @param events data.table of events generated by \code{returnStateEvents}
#' @param action One of "merge" or "exclude" for specifying the method of
#'   handling mergeable tracks
#' @param max_locs Maximum number of locations for a track to be mergeable. Set to Inf to not consider.
#' @param max_time Maximum time elapsed (seconds) for a track to be mergeable. Set to Inf to not consider.
#' @param max_dist Maximum distance (meters) traveled while on track to be mergeable. Set to Inf to not consider.
#'
#' @return Modifies events data.table by reference

moveMerger <- function(events, small_track_action = "merge", max_locs = 1, max_time = 600, max_dist = 100){
  # condition <- events[n_locations <= max_locs & ts <= max_time, which = TRUE]
  # set(events,
  #     j = c("new_stop_id",
  #           "new_within_stop"),
  #     value = list(events[["new_stop_id"]],
  #                  !is.na(events[["stop_id"]]))
  # )
  # set(events,
  #     j = "new_stop_id",
  #     value = events[["new_stop_id"]]
  #     )

  events[, mergeable := FALSE]
  events[state == "moving",
         mergeable := n_locations <= max_locs &
           ((end_time - begin_time) <= max_time) &
           raw_travel_dist <= max_dist]
  events[, `:=`(
    new_state_id = new_state_id - cumsum(mergeable),
    new_state = state
  )]

  if (action == "merge") {
    events[mergeable == TRUE, `:=`(new_state = "stopped"
    )]
    events[, mergeable := NULL]
  } else if (action == "exclude") {
    events[mergeable == TRUE,
           `:=`(new_state = "excluded",
                new_state_id = NA)]
    # events[, mergeable := NULL]
  }
  events[]
}
