#' Move Merger
#'
#' Discards move events (tracks) between stop events that should be discarded
#' during merging. This is based on the researcher-decided total number of
#' allowable locations that the discarded track can consist of, as well as a
#' maximum total time length that may elapse. Tracks are merged into the
#' preceding stop, which is an arbitrary decision. Future versions of this
#' should consider either discarding the measurement or assigning it to the
#' closest stop.
#'
#' @param events data.table of events generated by \code{returnStateEvents}
#' @param max_locs Maximum number of locations for a track to be mergeable
#' @param max_time Maximum time elapsed for a track to be mergeable
#'
#' @return Modifies events by reference
#' @export

moveMerger <- function(events, max_locs = 1, max_time = 600){
  # condition <- events[n_locations <= max_locs & ts <= max_time, which = TRUE]
  # set(events,
  #     j = c("new_stop_id",
  #           "new_within_stop"),
  #     value = list(events[["new_stop_id"]],
  #                  !is.na(events[["stop_id"]]))
  # )
  # set(events,
  #     j = "new_stop_id",
  #     value = events[["new_stop_id"]]
  #     )
  events[, `:=`(
    new_stop_id = state_id - cumsum(is.na(meanlat) &
                                      n_locations <= max_locs &
                                      ts <= max_time)
  )]
  #
  # set(events,
  #     i = condition,
  #     j = c("new_stop_id",
  #           "new_within_stop"),
  #     value = list(
  #       events[["state_id"]][condition] - 1,
  #       TRUE)
  # )
}
