# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Haversine Distance Between Two Points
#' Calculate the great circle distance between two points on Earth
#' using the Haversine formula.
#'
#' @param lat1 Latitude of first point (decimal degrees)
#' @param lon1 Longitude of first point (decimal degrees)
#' @param lat2 Latitude of second point (decimal degrees)
#' @param lon2 Longitude of second point (decimal degrees)
#' @return Distance in meters
#' @export
#' @examples
#' # Distance between two points
#' haversine_cpp(52.092839, 5.1299311, 52.092698, 5.135613)
haversine_cpp <- function(lat1, lon1, lat2, lon2) {
    .Call(`_stopdetection_haversine_cpp`, lat1, lon1, lat2, lon2)
}

#' Vectorized Haversine Distance (Paired)
#' Calculate distances between corresponding pairs of points.
#'
#' @param lat1 Vector of starting latitudes
#' @param lon1 Vector of starting longitudes
#' @param lat2 Vector of ending latitudes
#' @param lon2 Vector of ending longitudes
#' @return Vector of distances in meters
#' @export
#' @examples
#' haversine_vec(c(52.09, 52.10), c(5.12, 5.13),
#'               c(52.10, 52.11), c(5.13, 5.14))
haversine_vec <- function(lat1, lon1, lat2, lon2) {
    .Call(`_stopdetection_haversine_vec`, lat1, lon1, lat2, lon2)
}

#' Vectorized Haversine Distance (Sequential)
#' Calculate distances between consecutive points in a trajectory.
#'
#' @param lat Vector of latitudes
#' @param lon Vector of longitudes
#' @return Vector of distances in meters (length n-1)
#' @export
#' @examples
#' # Distance between consecutive points
#' haversine_seq(c(52.09, 52.10, 52.11), c(5.12, 5.13, 5.14))
haversine_seq <- function(lat, lon) {
    .Call(`_stopdetection_haversine_seq`, lat, lon)
}

#' @title Stop Detection Algorithm (C++ Backend)
#'
#' @description
#' Low-level C++ implementation of the stop detection algorithm.
#' Users should typically call [stopFinderFast()] instead.
#'
#' @param lat Numeric vector of latitudes (decimal degrees)
#' @param lon Numeric vector of longitudes (decimal degrees)
#' @param time Numeric vector of timestamps
#' @param thetaD Distance threshold in meters
#' @param thetaT Time threshold (same units as `time`)
#'
#' @return Integer vector of stop initiation indices (1-indexed), with
#'   `NA` for points not belonging to a stop.
#'
#' @seealso [stopFinderFast()] for the recommended interface
#' @family stop-detection
#' @keywords internal
#' @export
stopFinder_cpp <- function(lat, lon, time, thetaD, thetaT) {
    .Call(`_stopdetection_stopFinder_cpp`, lat, lon, time, thetaD, thetaT)
}

